_版权所有  2019 Starkware Industries Ltd。根据 Apache 许可证版本 2.0（“许可证”）许可。除非符合许可证的规定，否则您不得使用此文件。您可以在
https://www.starkware.co/open-source-license/ 获取许可证的副本。除非适用法律要求或书面同意，否则根据许可证分发的软件是基于“按原样”分发的，没有任何形式的明示或暗示的保证或条件。请参阅许可证以了解许可权限和限制的具体语言。_

== Part 3: FRI 承诺

* https://www.youtube.com/watch?v=Y0uJz9VL3Fo[视频讲解 (youtube)]
* https://starkware.co/wp-content/uploads/2021/12/STARK101-Part1.pdf[幻灯片
(PDF)]

== 加载上一个会话

运行下一个单元格以加载相关变量。像往常一样 - 运行需要一段时间。

[source,python]
----
from channel import Channel
from field import FieldElement
from merkle import MerkleTree
from polynomial import interpolate_poly, Polynomial
from tutorial_sessions import part1, part2

cp, cp_eval, cp_merkle, channel, eval_domain = part2()
print("Success")
----

== FRI 折叠

本部分的目标是构建FRI层并对其进行承诺。为了获得每一层，我们需要：

. 生成该层的域 (来自上一层域)。
. 生成该层的多项式 (来自上一层的多项式和域)。
. 在这个域上评估多项式 - *这就是下一层 FRI 层*.

== 域的生成

第一个 FRI 域就是第一部分生成的 `eval_domain`，即 8192 阶群的余类。每个后续的 FRI 域通过取前一个 FRI 域的前一半（舍弃后一半）并平方它的每个元素得到的。

正式地说 - 我们通过以下方式获得 `eval_domain`：

[latexmath]
++++
\[w, w\cdot h, w\cdot h^2, ..., w\cdot h^{8191}\]
++++

因此，下一层将是：

[latexmath]
++++
\[w^2, (w\cdot h)^2, (w\cdot h^2)^2, ..., (w\cdot h^{4095})^2\]
++++

请注意， 对 `eval_domain` 中的每个元素的后一半进行平方，得到的结果与对前一半进行平方完全相同。这对于下一层也是成立的。例如：

[source,python]
----
print(eval_domain[100] ** 2)
half_domain_size = len(eval_domain) // 2
print(eval_domain[half_domain_size + 100] ** 2)
----

同样地，第三层的领域将是：

[latexmath]
++++
\[w^4, (w\cdot h)^4, (w\cdot h^2)^4, ..., (w\cdot h^{2047})^4\]
++++

以此类推。

编写一个名为 `next_fri_domain` 的函数，该函数将先前的域作为参数，并输出下一个域。

解决方案：

[source,python]
----
def next_fri_domain(fri_domain):
    return [x ** 2 for x in fri_domain[:len(fri_domain) // 2]]
----

运行测试：

[source,python]
----
# Test against a precomputed hash.
from hashlib import sha256
next_domain = next_fri_domain(eval_domain)
assert '5446c90d6ed23ea961513d4ae38fc6585f6614a3d392cb087e837754bfd32797' == sha256(','.join([str(i) for i in next_domain]).encode()).hexdigest()
print('Success!')
----

== FRI 折叠运算符

第一个 FRI 多项式就是组合多项式，即 `cp`。 每个后续的 FRI 多项式都是通过以下方式获得的：

. 获取一个随机的域元素 latexmath:[$\beta$] (通过调用 `Channel.receive_random_field_element`)。
. 将前一个多项式的奇数系数乘以 latexmath:[$\beta$]。
. 将连续的系数对（偶-奇）相加。

正式地说，假设第 k 个多项式的系数为 latexmath:[$< m$] (其中 latexmath:[$m$] 是 2 的次方)：

[latexmath]
++++
\[p_{k}(x) := \sum _{i=0} ^{m-1} c_i x^i\]
++++

那么，次数为  $< \frac m 2 $ 的第 (k+1) 个多项式将是：

[latexmath]
++++
\[p_{k+1}(x) := \sum _{i=0} ^{  m / 2 - 1 } (c_{2i} + \beta \cdot c_{2i + 1}) x^i\]
++++

编写一个名为 `next_fri_polynomial` 的函数，改函数的多项式和一个域元素（我们称之为 latexmath:[$\beta$]）作为参数，并返回“折叠”后的下一个多项式。

请注意；

. `Polynomial.poly` 包含多项式字数的列表，自由项在前，最高次项在后，因此如果 latexmath:[$x^i$]` 的系数为 latexmath:[$x^i$]，则 p.poly[i] == u` 。
. `Polynomial`的默认构造函数将系数列表作为参数。因此，可以通过调用 `Polynomial(l)` 从系数列表 `l` 实现多项式。

解决方案：

[source,python]
----
def next_fri_polynomial(poly,  beta):
    odd_coefficients = poly.poly[1::2]
    even_coefficients = poly.poly[::2]
    odd = beta * Polynomial(odd_coefficients)
    even = Polynomial(even_coefficients)
    return odd + even
----

运行测试：

[source,python]
----
next_p = next_fri_polynomial(cp, FieldElement(987654321))
assert '6bff4c35e1aa9693f9ceb1599b6a484d7636612be65990e726e52a32452c2154' == sha256(','.join([str(i) for i in next_p.poly]).encode()).hexdigest()
print('Success!')
----

== 把它放在一起，以获得下一个 FRI 层

编写一个名为 `next_fri_layer` 的函数，该函数接受一个一个多项式、一个域和一个域元素（再次是 latexmath:[$\beta$]），并返回下一个多项式、下一个域以及在这个下一个域上对这个下一个多项式的求值。

解决方案：

[source,python]
----
def next_fri_layer(poly, domain, beta):
    next_poly = next_fri_polynomial(poly, beta)
    next_domain = next_fri_domain(domain)
    next_layer = [next_poly(x) for x in next_domain]
    return next_poly, next_domain, next_layer
----

运行测试：

[source,python]
----
test_poly = Polynomial([FieldElement(2), FieldElement(3), FieldElement(0), FieldElement(1)])
test_domain = [FieldElement(3), FieldElement(5)]
beta = FieldElement(7)
next_p, next_d, next_l = next_fri_layer(test_poly, test_domain, beta)
assert next_p.poly == [FieldElement(23), FieldElement(7)]
assert next_d == [FieldElement(9)]
assert next_l == [FieldElement(86)]
print('Success!')
----

== 生成 FRI 承诺

我们现在已经开发了编写 `FriCommit` 方法所需的工具，其中包含主要的 FRI 承诺循环。

它接受以下5个参数：

. 组合多项式，也是第一个 FRI 多项式，即 `cp`。
. 阶为 8192 的余元集，也是第一个 FRI 域，即 `eval_domain`。
. 前者在后者上的求值，也是第一个 FRI 层，即 `cp_eval`。
. 从这些评估构建的第一个 Merkle Tree（我们将使每个 FRI 层拥有一个），即 `cp_merkle`。
. 一个通道对象，即 `channel`。

该方法相应地返回 4 个列表：

. FRI 多项式。
. FRI 域。
. FRI 层。
. FRI Merkle trees。

该方法包含一个循环，在每次迭代中，我们使用每个列表中的最后一个元素扩展这四个列表。当最后一个 FRI 多项式的次数为 0 时，也就是当最后一个 FRI 多项式只是一个常数时，迭代应该停止。然后，它应该通过通道发送这个常数（即多项式的自由项）。`Channel` 类仅支持发送字符串，因此在发送之前，请确保将要发送的任何内容转换为字符串。

解决方案：

[source,python]
----
def FriCommit(cp, domain, cp_eval, cp_merkle, channel):    
    fri_polys = [cp]
    fri_domains = [domain]
    fri_layers = [cp_eval]
    fri_merkles = [cp_merkle]
    while fri_polys[-1].degree() > 0:
        beta = channel.receive_random_field_element()
        next_poly, next_domain, next_layer = next_fri_layer(fri_polys[-1], fri_domains[-1], beta)
        fri_polys.append(next_poly)
        fri_domains.append(next_domain)
        fri_layers.append(next_layer)
        fri_merkles.append(MerkleTree(next_layer))
        channel.send(fri_merkles[-1].root)   
    channel.send(str(fri_polys[-1].poly[0]))
    return fri_polys, fri_domains, fri_layers, fri_merkles
----

运行测试：

[source,python]
----
test_channel = Channel()
fri_polys, fri_domains, fri_layers, fri_merkles = FriCommit(cp, eval_domain, cp_eval, cp_merkle, test_channel)
assert len(fri_layers) == 11, f'Expected number of FRI layers is 11, whereas it is actually {len(fri_layers)}.'
assert len(fri_layers[-1]) == 8, f'Expected last layer to contain exactly 8 elements, it contains {len(fri_layers[-1])}.'
assert all([x == FieldElement(-1138734538) for x in fri_layers[-1]]), f'Expected last layer to be constant.'
assert fri_polys[-1].degree() == 0, 'Expected last polynomial to be constant (degree 0).'
assert fri_merkles[-1].root == '1c033312a4df82248bda518b319479c22ea87bd6e15a150db400eeff653ee2ee', 'Last layer Merkle root is wrong.'
assert test_channel.state == '61452c72d8f4279b86fa49e9fb0fdef0246b396a4230a2bfb24e2d5d6bf79c2e', 'The channel state is not as expected.'
print('Success!')
----

运行以下单元格，使用您的通道对象执行该函数，并打印到目前为止的证明：

[source,python]
----
fri_polys, fri_domains, fri_layers, fri_merkles = FriCommit(cp, eval_domain, cp_eval, cp_merkle, channel)
print(channel.proof) 
----
