_版权所有  2019 Starkware Industries Ltd。根据 Apache 许可证版本 2.0（“许可证”）许可。除非符合许可证的规定，否则您不得使用此文件。您可以在
https://www.starkware.co/open-source-license/ 获取许可证的副本。除非适用法律要求或书面同意，否则根据许可证分发的软件是基于“按原样”分发的，没有任何形式的明示或暗示的保证或条件。请参阅许可证以了解许可权限和限制的具体语言。_

== 第二部分：约束条件

* https://www.youtube.com/watch?v=Y0uJz9VL3Fo[视频讲解 (youtube)]
* https://starkware.co/wp-content/uploads/2021/12/STARK101-Part1.pdf[幻灯片
(PDF)]

在这一部分，我们将跟踪 `a` 创建一组约束条件。这些约束条件将是跟踪单元格中的表达式，如果且仅如果跟踪表示 FibonacciSq 的有效计算，则这些表达式将是多项式（而不是有理函数）。我们将通过三个步骤实现这一目标：

. 首先我们需要指定我们关心的约束条件 (the *FibonacciSq 约束条件*)。
. 将这些约束条件转化为 *多项式约束条件*。
. 最后，将它们转化为 *有理函数*，当且仅当原始约束条件成立时，这些有理函数表示多项式。

== 第一步 - FibonacciSq 约束条件

使 `a` 成为一个正确的 FibonacciSq 序列的跟踪，证明我们的论断：

. 第一个元素必须为1，即 latexmath:[$a[0] = 1$]。
. 最后一个元素必须为2338775057，即 latexmath:[$a[1022] = 2338775057$]。
. FibonacciSq 规则必须适用，即对于每个 latexmath:[$i<1021$]，latexmath:[$a[i+2]=a[i+1]^2+a[i]^2$]。

== 第二步 - 多项式约束条件

回顾下， `f` 是跟踪域上的多项式，在 latexmath:[$G \setminus \{g^{1023}\}$] 上恰好评估为 `a`，其中 
latexmath:[$G=\{g^i : 0\leq i\leq 1023\}$] 是由 latexmath:[$g$] 生成的“小”群。

我们现在将上述三个约束条件重写为关于 `f` 的多项式约束条件的形式：

. latexmath:[$a[0] = 1$] 被转化为多项式 latexmath:[$f(x) - 1$], 在 latexmath:[$x = g^0$] 处评估为 0 （请注意，latexmath:[$g^0$] 等于 latexmath:[$1$]）。
. latexmath:[$a[1022] = 2338775057$] 被转化为多项式 latexmath:[$f(x) - 2338775057$]，在 latexmath:[$x = g^{1022}$] 处评估为 0。
. 对于每个 latexmath:[$i<1021$]，latexmath:[$a[i+2]=a[i+1]^2+a[i]^2$] 被转化为多项式 latexmath:[$f(g^2 \cdot x) - (f(g \cdot x))^2 - (f(x))^2$]，在 latexmath:[$x \in G \backslash \{g^{1021}, g^{1022}, g^{1023}\}$] 处评估为 0。

== 实践操作

首先，由于这是与第一部分不同的独立笔记本，让我们运行以下代码片段，以便将所有变量及其正确的值带到此处。请注意，这可能需要多达30秒的时间，因为它会重新运行多项式插值。

[source,python]
----
from channel import Channel
from field import FieldElement
from merkle import MerkleTree
from polynomial import interpolate_poly, X, prod
from tutorial_sessions import part1

a, g, G, h, H, eval_domain, f, f_eval, f_merkle, channel = part1()
print('Success!')
----

你将得到三个约束中的每一个，作为两个多项式的商，确保余数是零项式。

== 第三步 - 有理函数（实际上是多项式）

上述每个约束条件都由一个多项式 latexmath:[$u(x)$] 表示，该多项式在群 latexmath:[$G$] 的某些元素上评估为 latexmath:[$0$]。 也就是说，对于一些 latexmath:[$x_0, \ldots, x_k \in G$]，我们声称：

[latexmath]
++++
\[u(x_0) = \ldots = u(x_k) = 0\]
++++

（请注意，对于前两个约束条件，latexmath:[$k=0$] ，因为它们只涉及一个点，对于第三个约束条件，latexmath:[$k=1021$])。

这等于说，多项式 latexmath:[$u(x)$] 可以被所有 latexmath:[$\{(x-x_i)\}_{i=0}^k$] 作为多项式整除，或者相当于被

[latexmath]
++++
\[\prod_{i=0}^k (x-x_i)\]
++++

因此，上述三个约束条件中的每一个都可以写成一个有理函数的形式：

[latexmath]
++++
\[\frac{u(x)}{\prod_{i=0}^k (x-x_i)}\]
++++

对于相应的 latexmath:[$u(x)$] 和 latexmath:[$\{x_i\}_{i=0}^k$]，在这一步中，我们将构造这三个有理函数，并证明它们确实是多项式。

== 第一个约束条件：

在第一个约束条件中，latexmath:[$f(x) - 1$] 和 latexmath:[$\{x_i\} = \{1\}$]。

我们现在将构造 *多项式* latexmath:[$p_0(x)=\frac{f(x) - 1}{x - 1}$]，确保
latexmath:[$f(x) - 1$] 确实可以被 latexmath:[$(x-1)$] 整除。

解决方案：

[source,python]
----
numer0 = f - 1
denom0 = X - 1
----

确保 latexmath:[$f(x) - 1$] 在 latexmath:[$x=1$] 处为零，通过确保在 latexmath:[$1$] 处评估这个多项式额结果为 latexmath:[$0$]。

latexmath:[$f(x) - 1$] 在 latexmath:[$1$] 处有一个根，这意味着它可以被 latexmath:[$(x - 1)$] 整除。 运行以下代码，确保 `numer0` 模除以 `denom0` 的余数为 latexmath:[$0$]，因此除法确实产生了一个多项式：

[source,python]
----
numer0 % denom0
----

运行以下代码，通过将 `numer0` 除以 `denom0` 来构造表示第一个约束条件的多项式 `p0`：

[source,python]
----
p0 = numer0 / denom0
----

运行测试：

[source,python]
----
assert p0(2718) == 2509888982
print('Success!')
----

== 第二个约束条件

类似地，构造表示第二个约束条件的多项式 `p1` ，其定义为：latexmath:[$p_1(x)= \frac{f(x) - 2338775057}{x - g^{1022}}$]。

解决方案：

[source,python]
----
numer1 = f - 2338775057
denom1 = X - g**1022
p1 = numer1 / denom1
----

运行测试：

[source,python]
----
assert p1(5772) == 232961446
print('Success!')
----

== 第三个约束条件 - 简洁性

最后一个约束的有理函数稍微复杂一些：

[latexmath]
++++
\[p_2(x) = \frac{f(g^2 \cdot x) - (f(g \cdot x))^2 - (f(x))^2}{\prod\limits_{i=0}^{1020} (x-g^i)}\]
++++

其分母可以改写，因此整个表达式更容易计算：

[latexmath]
++++
\[\frac{f(g^2 \cdot x) - (f(g \cdot x))^2 - (f(x))^2}{\frac{x^{1024} - 1}{(x-g^{1021})(x-g^{1022})(x-g^{1023})}}\]
++++

这是由平等关系得出的

[latexmath]
++++
\[\prod\limits_{i=0}^{1023} (x-g^i) = x^{1024} - 1\]
++++

您可以使用函数 `prod` 来验证这个等式。 `prod` 函数接受一个列表作为输入，并计算其乘积。

解决方案：

[source,python]
----
lst = [(X - g**i) for i in range(1024)]
prod(lst)
----

更多详情，请查看我们的题为 https://medium.com/starkware/arithmetization-ii-403c3b3f4355[Arithmetization
II] 的博客文章。

让我们停顿一下，看一个简单的例子，说明多项式是如何组成的。之后，我们将生成第三个约束。

== 多项式合成（小插曲）

创建两个多项式 latexmath:[$q(x) = 2x^2 +1$]、latexmath:[$r(x) = x - 3$]：

[source,python]
----
q = 2*X ** 2 + 1
r = X - 3
----

将多项式 latexmath:[$q$] 合成到多项式 latexmath:[$r$] 上，可以得到一个新的多项式：latexmath:[$q(r(x)) = 2(x-3)^2 + 1 = 2x^2-12x+19$] 运行以下代码，通过 `q` 合成到 `r` 上得到第三个多项式 `cmp` ，并验证 `cmp` 确实是 `q` 和 `r` 的合成。

[source,python]
----
cmp = q(r)
cmp
----

== 回到多项式约束条件

类似于构造 `p0` 和 `p1` 的方式，使用多项式合成构造第三个约束条件 `p2`。在此过程中，验证 latexmath:[$g^{1020}$] 是 *分子* 的根，而 latexmath:[$g^{1021}$] 不是。

解决方案：

[source,python]
----
numer2 = f(g**2 * X) - f(g * X)**2 - f**2
print("Numerator at g^1020 is", numer2(g**1020))
print("Numerator at g^1021 is", numer2(g**1021))
denom2 = (X**1024 - 1) / ((X - g**1021) * (X - g**1022) * (X - g**1023))

p2 = numer2 / denom2
----

运行测试：

[source,python]
----
assert p2.degree() == 1023, f'The degree of the third constraint is {p2.degree()} when it should be 1023.'
assert p2(31415) == 2090051528
print('Success!')
----

运行以下代码以观察约束多项式 `p0`、 `p1` 和 `p2` 的次数，它们都小于 latexmath:[$1024$]。这在下一部分中非常重要。

[source,python]
----
print('deg p0 =', p0.degree())
print('deg p1 =', p1.degree())
print('deg p2 =', p2.degree())
----

== 第四步 - 合成多项式

回顾一下， 我们正在将一个检查三个多项式约束条件的有效性的问题转化为检查每个有理函数 latexmath:[$p_0, p_1, p_2$] 是否为多项式的问题。

我们的协议使用一种成为
https://eccc.weizmann.ac.il/report/2017/134/[FRI] 的算法来实现这一点， 这将在下一部分中讨论。为了使证明简洁
（简短的），我们更喜欢使用一个有理函数而不是三个。为此，我们从 latexmath:[$p_0, p_1, p_2$] 中随机选择一个线性组合，称为 *合成多项式* （简称为 CP）。

[latexmath]
++++
\[CP(x) = \alpha_0 \cdot p_0(x) + \alpha_1 \cdot p_1(x) + \alpha_2 \cdot  p_2(x)\]
++++

其中 $\alpha_0, \alpha_1, \alpha_2 $ 是从验证者哪里获得的随机域元素，或者在我们的例子中，是从通信那里获得。

证明（有理函数） latexmath:[$CP$] 是一个多项式可以高概率确保 latexmath:[$p_0$]、
latexmath:[$p_1$]、latexmath:[$p_2$] 它们自身也是多项式。

在下一部分中，你将为一个等价的事实生成证明。但首先，让我们使用 `Channel.receive_random_field_element` 创建 `CP` 以获取 latexmath:[$\alpha_i$]。

解决方案：

[source,python]
----
def get_CP(channel):
    alpha0 = channel.receive_random_field_element()
    alpha1 = channel.receive_random_field_element()
    alpha2 = channel.receive_random_field_element()
    return alpha0*p0 + alpha1*p1 + alpha2*p2
----

运行测试：

[source,python]
----
test_channel = Channel()
CP_test = get_CP(test_channel)
assert CP_test.degree() == 1023, f'The degree of cp is {CP_test.degree()} when it should be 1023.'
assert CP_test(2439804) == 838767343, f'cp(2439804) = {CP_test(2439804)}, when it should be 838767343'
print('Success!')
----

== 关于合成多项式的承诺

最后，我们在评估域 (`eval_domain`) 上评估 latexmath:[$cp$]，在此基础上建立一个 Merkle tree，并把根发送到通信上。类似于在 LDE 轨迹上的承诺，就像我们在第一部分结束时做的那样。

解决方案：

[source,python]
----
def CP_eval(channel):
    CP = get_CP(channel)
    return [CP(d) for d in eval_domain]
----

在评估上构建一个 Merkle Tree，并把根发送到通信上。

解决方案：

[source,python]
----
channel = Channel()
CP_merkle = MerkleTree(CP_eval(channel))
channel.send(CP_merkle.root)
----

测试你的代码：

[source,python]
----
assert CP_merkle.root == 'a8c87ef9764af3fa005a1a2cf3ec8db50e754ccb655be7597ead15ed4a9110f1', 'Merkle tree root is wrong.'
print('Success!')
----
