_版权所有  2019 Starkware Industries Ltd。根据 Apache 许可证版本 2.0（“许可证”）许可。除非符合许可证的规定，否则您不得使用此文件。您可以在
https://www.starkware.co/open-source-license/ 获取许可证的副本。除非适用法律要求或书面同意，否则根据许可证分发的软件是基于“按原样”分发的，没有任何形式的明示或暗示的保证或条件。请参阅许可证以了解许可权限和限制的具体语言。_

== 第四部分： 查询阶段

* https://www.youtube.com/watch?v=Y0uJz9VL3Fo[视频讲解 (youtube)]
* https://starkware.co/wp-content/uploads/2021/12/STARK101-Part1.pdf[幻灯片
(PDF)]

== 加载上一个会话

运行下一个单元格以加载相关变量。像往常一样 - 运行需要一段时间。

[source,python]
----
from channel import Channel
from tutorial_sessions import part1, part3 

_, _, _, _, _, _, _, f_eval, f_merkle, _ = part1()
fri_polys, fri_domains, fri_layers, fri_merkles, _ = part3()

print('Success!')
----

== 在查询上取消承诺

在这一部分中，我们的目标是生成验证前三部分承诺所需的所有信息。在这一部分中，我们编写了两个函数：

. `decommit_on_fri_layers` - 通过通道发送数据，显示每个 FRI 层在指定索引处进行采样时与其他层一致。
. `decommit_on_query` - 发送取消跟踪所需的数据，然后调用 `decommit_on_fri_layers`。

== 在 FRI 层取消承诺

实现 `decommit_on_fri_layers` 函数。该函数获取一个索引和一个通道，并通过通道发送相关数据，以验证 FRI 层的正确性。更具体地说，它在 `fri_layers` 和 `fri_merkles` 上进行迭代，并在每次迭代中按照以下顺序发送以下数据： （按所述顺序排列）：

. 给定索引处的 FRI 层元素（使用 `fri_layers`）。
. 其认证路径（使用来自 `fri_merkles` 的相应的 Merkle Tree）。
. 元素的 FRI 兄弟（即，如果元素是 latexmath:[$cp_i(x)$]，则其兄弟是latexmath:[$cp_i(-x)$]，其中 latexmath:[$cp_i$] 是当前层的多项式，而 latexmath:[$x$] 是当前层域中的一个元素）。
. 元素兄弟的认证路径（使用相同的 Merkle Tree）。

要获取元素的认证路径，请每次使用 `MerkleTree` 类的 `get_authentication_path()` 方法，并使用相应的索引。请注意，元素兄弟的索引等于 (idx + latexmath:[$\frac k 2$]) mod latexmath:[$k$]，其中 latexmath:[$k$] 是相关 FRI 层的长度。请注意，我们 *不* 发送元素的认证路径。在最后一层中，所有元素都相等，与查询无关，因为它们是常数多项式的评估。

_(记得在发送通道之前将非字符串变量转换为字符串。)_

解决方案：

[source,python]
----
def decommit_on_fri_layers(idx, channel):
    for layer, merkle in zip(fri_layers[:-1], fri_merkles[:-1]):
        length = len(layer)
        idx = idx % length
        sib_idx = (idx + length // 2) % length        
        channel.send(str(layer[idx]))
        channel.send(str(merkle.get_authentication_path(idx)))
        channel.send(str(layer[sib_idx]))
        channel.send(str(merkle.get_authentication_path(sib_idx)))       
    channel.send(str(fri_layers[-1][0]))
----

测试你的代码：

[source,python]
----
# Test against a precomputed hash.
test_channel = Channel()
for query in [7527, 8168, 1190, 2668, 1262, 1889, 3828, 5798, 396, 2518]:
    decommit_on_fri_layers(query, test_channel)
assert test_channel.state == 'ad4fe9aaee0fbbad0130ae0fda896393b879c5078bf57d6c705ec41ce240861b', 'State of channel is wrong.'
print('Success!')
----

== 在跟踪多项式上取消承诺

为了证明我们取消承诺的 FRI 层确实是从组合多项式的评估生成的，我们还必须发送：

. 带有其认证路径的 latexmath:[$f(x)$] 的值。
. 带有其认证路径的 latexmath:[$f(gx)$] 的值。
. 带有其认证路径的 latexmath:[$f(g^2x)$] 的值。知道组合多项式的随机系数的验证器可以计算其在 latexmath:[$x$] 处的评估。并将其与从第一个 FRI 层发送的第一个元素进行比较。

因此，函数 `decommit_on_query` 应该通过通道发送上述内容（1、2和3），然后调用 `decommit_on_fri_layers`。

重要的是，尽管 latexmath:[$x, gx, g^2x$] 在跟踪中是连续的元素（模组大小为 latexmath:[$|G|$]），但这些点中 `f_eval` 的评估实际上相隔 8 个元素。原因是我们在第一部分中将跟踪“扩展”到其大小的 8 倍，以获得 Reed Solomon 码字。

_提醒：`f_eval` 是组合多项式的评估，`f_merkle` 是相应的Merkle Tree。_

解决方案：

[source,python]
----
def decommit_on_query(idx, channel): 
    assert idx + 16 < len(f_eval), f'query index: {idx} is out of range. Length of layer: {len(f_eval)}.'
    channel.send(str(f_eval[idx])) # f(x).
    channel.send(str(f_merkle.get_authentication_path(idx))) # auth path for f(x).
    channel.send(str(f_eval[idx + 8])) # f(gx).
    channel.send(str(f_merkle.get_authentication_path(idx + 8))) # auth path for f(gx).
    channel.send(str(f_eval[idx + 16])) # f(g^2x).
    channel.send(str(f_merkle.get_authentication_path(idx + 16))) # auth path for f(g^2x).
    decommit_on_fri_layers(idx, channel)    
----

测试你的代码：

[source,python]
----
# Test against a precomputed hash.
test_channel = Channel()
for query in [8134, 1110, 1134, 6106, 7149, 4796, 144, 4738, 957]:
    decommit_on_query(query, test_channel)
assert test_channel.state == '16a72acce8d10ffb318f8f5cd557930e38cdba236a40439c9cf04aaf650cfb96', 'State of channel is wrong.'
print('Success!')
----

== 在一组查询上取消承诺

为了完成证明，证明器从通道获取一组随机查询，即从 0 到 8191 的索引，并对每个查询进行取消承诺。

使用刚刚实现的函数 `decommit_on_query()` 和`Channel.receive_random_int` 来生成 3 个随机查询，并对每个查询进行取消承诺。

解决方案：

[source,python]
----
def decommit_fri(channel):
    for query in range(3):
        # Get a random index from the verifier and send the corresponding decommitment.
        decommit_on_query(channel.receive_random_int(0, 8191-16), channel)
----

测试你的代码：

[source,python]
----
test_channel = Channel()
decommit_fri(test_channel)
assert test_channel.state == 'eb96b3b77fe6cd48cfb388467c72440bdf035c51d0cfe8b4c003dd1e65e952fd', 'State of channel is wrong.' 
print('Success!')
----

== 证明时间！

运行下面的单元格，将所有先前的代码以及您在此部分编写的函数绑定在一起，并打印出证明。

[source,python]
----
import time
from tutorial_sessions import part1, part3 

start = time.time()
start_all = start
print("Generating the trace...")
_, _, _, _, _, _, _, f_eval, f_merkle, _ = part1()
print(f'{time.time() - start}s')
start = time.time()
print("Generating the composition polynomial and the FRI layers...")
fri_polys, fri_domains, fri_layers, fri_merkles, channel = part3()
print(f'{time.time() - start}s')
start = time.time()
print("Generating queries and decommitments...")
decommit_fri(channel)
print(f'{time.time() - start}s')
start = time.time()
print(channel.proof)
print(f'Overall time: {time.time() - start_all}s')
print(f'Uncompressed proof length in characters: {len(str(channel.proof))}')
----
